name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: fail scenarios
      run: |
        cd examples \
        && cargo run 2>&1 | grep -q 'exactly one' \
        && cargo run --features "a","b" 2>&1 | grep -q 'mutually exclusive'

    - name: pass scenarios
      run: |
        cd examples && cargo run --features "a"
